// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1 shiftlef()", "[example]")
{
	const int SIZE = 10;
	int numbers[SIZE] = {10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
	int N = 5;
	int result = 1, idx = 0;
	shiftleft(numbers, SIZE, N);
	cout << numbers[N] << endl;
	for (int i = 0; i < N; i++)
	{
		if (numbers[i] != (10 + N + i))
		{
			result = 0;
			idx = i;
			break;
		}
	}

	INFO("shiftleft() function does not have the reverse order of the original array " << numbers[idx]);
	REQUIRE(result == 1);
	cout << "****************************************\n";
}
// tests for exercise 2
